services:
  ktmuslave:
    build:
      context: .
    depends_on:
      - ktmuscrap
      - redis
    networks:
      - local
    volumes:
      - type: bind
        source: ./data/docker/ktmuslave
        target: /ktmuslave/data
        bind:
          create_host_path: true
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
  ktmuscrap:
    build: https://github.com/kerdl/ktmuscrap.git
    ports:
      - 8080:8080
    networks:
      - local
    volumes:
      - type: bind
        source: ./data/docker/ktmuscrap
        target: /ktmuscrap/data
        bind:
          create_host_path: true
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
  redis:
    image: redis/redis-stack-server:latest
    environment:
      - REDIS_ARGS=--save 10 1 --loglevel warning
    ports:
      - 6379:6379
    networks:
      - local
    volumes:
      - type: bind
        source: ./data/docker/redis
        target: /data
        bind:
          create_host_path: true
    restart: always
networks:
  local:
    driver: bridge
