class BackendError(BaseException):
    ...

class FrontendError(BaseException):
    ...


""" ## Backend errors """
class NoSpaceSpecified(BackendError): ...
class NoContext(BackendError): ...
class SpaceMixing(BackendError): ...
class NoMentionString(BackendError): ...
class NoEverythingWithDebugOn(BackendError): ...
